make group list page
msengine/first_android pull request #4
Opened 2017-12-21 09:40 UTC by onlyhisson

2017-12-21 10:12 UTC, UniverseHan requested changes
몇가지 수정사항 달았어요

2017-12-21 10:12 UTC, UniverseHan commented on app/src/main/java/com/example/byhisson/fragmentex/GroupListAdt.java
> +public class GroupListAdt extends ArrayAdapter<GroupVO> {
Adt라는 줄임말 말고 Adaptor 사용

2017-12-21 10:12 UTC, UniverseHan commented on app/src/main/java/com/example/byhisson/fragmentex/GroupListAdt.java
> +        final GroupVO vo = datas.get(position);
vo는 VewObject의 약자인가요?? 약어는 가능하면 피하도록

2017-12-21 10:12 UTC, UniverseHan commented on app/src/main/java/com/example/byhisson/fragmentex/GroupListAdt.java
> +        final GroupVO vo = datas.get(position);
변수명이 vo면 뭔지 알 수가 없어요 명시적인 변수명으로 변경

2017-12-21 10:12 UTC, UniverseHan commented on app/src/main/java/com/example/byhisson/fragmentex/GroupListAdt.java
> +        if (vo.getGroupOrganisation().equals("company")) {
vo.getGroupOrganisation() 보다는 group.getOrganisation() 이 좋아보여요

2017-12-21 10:12 UTC, UniverseHan commented on app/src/main/java/com/example/byhisson/fragmentex/GroupListAdt.java
> +        }
위 로직은 오가니제이션 이미지를 얻는것 같으니 getImageOfOrganization(organization) 처럼 사용할 수 있게 함수로 분리하면 더 좋을것 같아요

2017-12-21 10:12 UTC, UniverseHan commented on app/src/main/java/com/example/byhisson/fragmentex/GroupVO.java
> +public class GroupVO {
클래스명 좀 거 명시적인 이름으로 그냥 Group이 좋은것 같아요.

2017-12-21 10:12 UTC, UniverseHan commented on app/src/main/res/layout/group_custom_item.xml
> +        android:id="@+id/group_item_type_image"
type은 명칭에서 빼도 될듯

2017-12-22 03:32 UTC, onlyhisson commented on app/src/main/java/com/example/byhisson/fragmentex/GroupListAdt.java
> +        if (vo.getGroupOrganisation().equals("company")) {
vo 를 group 로 변경합니다.

2017-12-27 14:37 UTC, merged